version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config-postgres.properties
      - JAVA_OPTS=-Xms1g -Xmx4g
      - server.servlet.context-path=/conductor-server
    volumes:
      - ./config-postgres.properties:/app/config/config-postgres.properties    
    image: ghcr.io/cnr-anac/conductor-community-server:latest
    container_name: conductor-server
    ports:
      - 9080:8080
    extra_hosts:
      - "dica33.ba.cnr.it:150.145.95.73"      
    links:
      - conductor-postgres:postgresdb
    depends_on:
      conductor-postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  conductor-postgres:
    image: postgres
    ports:
      - 5432
    command: postgres -c max_connections=1000      
    environment:
      - POSTGRES_USER=conductor
      - POSTGRES_PASSWORD=conductor
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/5432'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
